### ISSUE TITLE
Soul Stone Fussion Failure caused a duplication glitch(might be shadow type one)

### ISSUE THREAD

**Issue by hallowedzen** [comphack/comp_hack#998] opened 2019-06-26 02:44 UTC
Was doing my very first soul stone fussion and at failure it reproduced the item to be soul stoned into my inventory. In game names:(NeraJinx(my synther),(Neloc(main character)) Item disappeared upon relog, might be a shadow item duplication glitch then.

**Comment by HACKfrost** [comment] 2019-06-26 02:58
This is a duplicate of #975. From what I understand it is a shadow copy so a player with the dupe would get screwed :P

**Closed by HACKfrost** 2019-06-26 02:58 UTC
