### ISSUE TITLE
consecutive attack (lucifuge purs skills) transfer ?

### ISSUE THREAD

**Issue by Gricros** [comphack/comp_hack#1315] opened 2020-12-12 14:20 UTC
seems like this passives can be stacked if you cheap your way with demon fusion is this intended ?
![purs](https://user-images.githubusercontent.com/49335887/101986297-2ab8c080-3c85-11eb-886a-6d3144afe157.png)

**Comment by compomega** [comment] 2020-12-12 15:43
Thank you for the issue. The skills in question can be transferred through fusion. This behavior is defined in the client data and there is no specific code in the server that creates this behavior. It is working as intended. If a player finds it easier to obtain the skills through fusion, they are welcome to do so. Of course, after fusion the skill would need to either be re-fused (which would remove all reunion work) or bought through SP.

**Closed by compomega** 2020-12-12 15:43 UTC
Labels: question
