### ISSUE TITLE
Clan invites between certain players are not being sent correctly.

### ISSUE THREAD

**Issue by s4trace** [comphack/comp_hack#1041] opened 2019-08-12 19:16 UTC
Sadly I'm not sure how to reproduce this bug, as I've only run into it a few times without any solid clues as to what causes it. It involves clan invitations not going through between certain players.

**Bug Description:**
1. Player A invites Player B in a clan.
2. Player A gets a message in his chat saying "Player B has been invited to X Clan".
3. Player B never gets a notification that they've been invited to a clan and cannot join.
4. Player C invites Player B to the same clan, they get the notification and can join normally.

**Expected Behavior**
Player A should be able to invite Player B to a clan.

**Actual Behavior**
Player A is unable to invite Player B to a clan.

Invitation being sent multiple times and the other user not being notified. Please excuse the quality.
![invitation](https://user-images.githubusercontent.com/15641237/62891449-6caebb00-bd4e-11e9-800b-e4e072c35626.png)

Same invitation sent by me after the previous one failed three times, worked perfectly fine.
![invitationsuccess](https://user-images.githubusercontent.com/15641237/62891535-9f58b380-bd4e-11e9-8d53-eeea5c3c5874.png)

**Comment by HACKfrost** [comment] 2019-10-27 21:21
Short of the clan not being loaded when you started the game or the world message queue not processing messages, I don't see a code path that would not send a response to the requesting player. I can add a response for the first condition but I'm not sure how to reproduce this. Has this happened again since you reported this?

**Comment by s4trace** [comment] 2019-10-29 17:11
I have not run into this issue again ever since then no.

**Comment by HACKfrost** [comment] 2019-10-29 17:13
Thanks for the response, lets close this out and keep an eye out for it happening again so we can grab a log from the server and re-open then. As it stands right now I don't see anything but server performance being weird to cause this.

**Closed by HACKfrost** 2019-10-29 17:13 UTC
Labels: bug, code, waiting feedback
