### ISSUE TITLE
"Updater Check" client patch not functioning as intended

### ISSUE THREAD

**Issue by alkalime** [comphack/comp_hack#1339] opened 2021-01-12 23:14 UTC
Recently on ReIMAGINE (using comp_updater v4.12.2, comp_client 1.8.0) we enabled the "Updater Check" patch. Many users on Windows 10 were unable to launch the client at all even when launching through the updater. One user said that if they set the updater to Windows 8 compatibility mode it works.
We have since turned this feature off for end users.
I am unable to personally test this issue because I'm using Linux and it seems to work perfectly fine using wine.

**Comment by compomega** [comment] 2021-01-13 12:02
This patch is functioning on Windows 10 in my testing so the answer is not simply the version of Windows being used. I don't see why compatibility mode would be needed. The only issue I see is during the update to the v4.12.2 updater the files will be updated but the updater running will still be running v4.12.1 (or some older version). In this case, the first time the game is run, the player will get this error. Subsequent runs of the updater should start as v4.12.2 (if not it has been updated incorrectly for some reason) and should function correctly. If, when the error is seen, the player immediately tries to enable compatibility mode, it would most likely "fix" the problem because the application has been started again. If this is what happened, compatibility mode can be turned off again.

Unfortunately, the updater doesn't get restarted with the new version after update so the only way to "fix" this first time issue would be to update the updater to restart itself which would require the updater to again be updated first. This could be phased in (as could the v4.12.2 updater and the updater check enablement); however, there is no guarantee players will update during the first phase and may skip to the second phase causing the issue to appear.

@alkalime Can you have the players affected try turning off compatibility mode? Is there players who still see this issue when they are confirmed to be starting updater v4.12.2? If so, more information is needed to reproduce and determine the problem. If not, the issue may have been the "first time" issue describe above and no fix is needed.

**Comment by alkalime** [comment] 2021-01-14 16:12
I'll get in touch with the users who had this problem and report back.

**Comment by compomega** [comment] 2021-07-07 00:00
Is there still an issue/more information or can this be closed?

**Comment by compomega** [comment] 2022-01-15 00:19
Closing issue. Feel free to re-open the issue if more information is available.

**Closed by compomega** 2022-01-15 00:19 UTC
Labels: waiting feedback
