### ISSUE TITLE
Fusion skills should inflict status effects under specific conditions

### ISSUE THREAD

**Issue by Fizzlybub** [comphack/comp_hack#1117] opened 2020-01-12 01:41 UTC
In the description for this system, FC2 mentions that certain demon combinations result in status effects being added to the fusion skill. These status effects are not listed on the skill itself.

※フュージョン技を使用すると、敵にバステ付加の追加効果が出る事がある。（小種族が同じ場合？）【要確認】

There is very little information available online about this.

**Comment by HACKfrost** [comment] 2020-05-10 04:19
I'm fairly confident we will never be able to get enough information on how this worked or even if it was intended (I can't find an announcement talking about it). I'm going to close this as a "won't fix" as part of the code I'm putting in now that will allow hosts to customize the fusion skill FID to apply status effects to the target if they really want.

**Closed** 2020-05-15 03:10 UTC
Labels: bug, code, wontfix
